import {
	FaCheck,
	FaTimes,
	FaCog,
	FaUser,
	FaHome,
	FaStar,
	FaSearch,
	FaHeart,
	FaBell,
	FaArrowLeft,
	FaArrowRight,
	FaRegCopy,
	FaExclamationTriangle,
	FaCheckCircle,
	FaExclamationCircle,
	FaSun,
	FaMoon,
	FaPlay,
	FaEdit,
	FaTrash,
	FaInfoCircle,
	FaPlus,
	FaMinus,
	FaUpload,
	FaDownload,
	FaLock,
	FaUnlock,
	FaEye,
	FaEyeSlash,
	FaFilter,
	FaCalendar,
	FaCamera,
	FaEnvelope,
	FaPhone,
	FaGlobe,
	// Additional icons
	FaArrowUp,
	FaArrowDown,
	FaArrowCircleLeft,
	FaArrowCircleRight,
	FaArrowCircleUp,
	FaArrowCircleDown,
	FaChevronLeft,
	FaChevronRight,
	FaChevronUp,
	FaChevronDown,
	FaAngleLeft,
	FaAngleRight,
	FaAngleUp,
	FaAngleDown,
	FaBars,
	FaEllipsisH,
	FaEllipsisV,
	FaExternalLinkAlt,
	FaLink,
	FaPaperclip,
	FaBook,
	FaBookmark,
	FaFile,
	FaFileAlt,
	FaFolder,
	FaFolderOpen,
	FaImage,
	FaImages,
	FaVideo,
	FaMusic,
	FaVolumeUp,
	FaVolumeMute,
	FaMicrophone,
	FaMicrophoneSlash,
	FaHeadphones,
	FaPlayCircle,
	FaPause,
	FaPauseCircle,
	FaStop,
	FaStepForward,
	FaStepBackward,
	FaFastForward,
	FaFastBackward,
	FaRedo,
	FaUndo,
	FaSync,
	FaSpinner,
	FaAsterisk,
	FaQuestionCircle,
	FaInfo,
	FaCheckSquare,
	FaSquare,
	FaTh,
	FaThLarge,
	FaThList,
	FaList,
	FaListAlt,
	FaTable,
	FaChartBar,
	FaChartPie,
	FaChartLine,
	FaChartArea,
	FaMap,
	FaMapMarker,
	FaMapMarkerAlt,
	FaLocationArrow,
	FaCompass,
	FaFlag,
	FaTrophy,
	FaMedal,
	FaGift,
	FaShoppingCart,
	FaCreditCard,
	FaWallet,
	FaDollarSign,
	FaEuroSign,
	FaPoundSign,
	FaYenSign,
	FaBitcoin,
	FaApple,
	FaAndroid,
	FaWindows,
	FaLinux,
	FaGithub,
	FaGitlab,
	FaBitbucket,
	FaGit,
	FaCodeBranch,
	FaCode,
	FaBug,
	FaRocket,
	FaCloud,
	FaCloudUploadAlt,
	FaCloudDownloadAlt,
	FaServer,
	FaDatabase,
	FaShieldAlt,
	FaKey,
	FaUnlockAlt,
	FaUserCircle,
	FaUsers,
	FaUserPlus,
	FaUserMinus,
	FaUserCheck,
	FaUserTimes,
	FaUserEdit,
	FaUserFriends,
	FaEnvelopeOpen,
	FaAt,
	FaComment,
	FaComments,
	FaPaperPlane,
	FaBellSlash,
	FaCalendarAlt,
	FaCalendarCheck,
	FaCalendarTimes,
	FaClock,
	FaHourglass,
	FaHistory,
	FaClipboard,
	FaTasks,
	FaBriefcase,
	FaBuilding,
	FaCrown,
	FaGem,
	FaLightbulb,
	FaMagic,
	FaPuzzlePiece,
	FaSmile,
	FaFrown,
	FaMeh,
	FaThumbsUp,
	FaThumbsDown,
	FaHandPaper,
	FaHandPeace,
	FaHandPointUp,
	FaHandPointDown,
	FaHandPointLeft,
	FaHandPointRight,
	FaArrowAltCircleUp,
	FaArrowAltCircleDown,
	FaArrowAltCircleLeft,
	FaArrowAltCircleRight,
	FaCaretUp,
	FaCaretDown,
	FaCaretLeft,
	FaCaretRight,
	FaChevronCircleUp,
	FaChevronCircleDown,
	FaChevronCircleLeft,
	FaChevronCircleRight,
	FaDotCircle,
	FaCircle,
	FaRegCircle,
	FaRegDotCircle,
	FaRegSquare,
	FaRegCheckCircle,
	FaRegTimesCircle,
	FaRegQuestionCircle,
	FaRegSmile,
	FaRegFrown,
	FaRegMeh,
	FaRegBell,
	FaRegCalendarAlt,
	FaRegClock,
	FaRegComment,
	FaRegEnvelope,
	FaRegFileAlt,
	FaRegFolder,
	FaRegImage,
	FaRegListAlt,
	FaRegMap,
	FaRegPaperPlane,
	FaRegStar,
	FaRegUser,
} from 'react-icons/fa';
import type { IconName } from './IconTypes';

export const icons = {
	'check': FaCheck,
	'close': FaTimes,
	'settings': FaCog,
	'user': FaUser,
	'home': FaHome,
	'star': FaStar,
	'search': FaSearch,
	'heart': FaHeart,
	'bell': FaBell,
	'arrow-left': FaArrowLeft,
	'arrow-right': FaArrowRight,
	'copy': FaRegCopy,
	'warning': FaExclamationTriangle,
	'success': FaCheckCircle,
	'danger': FaExclamationCircle,
	'sun': FaSun,
	'moon': FaMoon,
	'play': FaPlay,
	'edit': FaEdit,
	'trash': FaTrash,
	'info': FaInfoCircle,
	'plus': FaPlus,
	'minus': FaMinus,
	'upload': FaUpload,
	'download': FaDownload,
	'lock': FaLock,
	'unlock': FaUnlock,
	'eye': FaEye,
	'eye-off': FaEyeSlash,
	'filter': FaFilter,
	'calendar': FaCalendar,
	'camera': FaCamera,
	'mail': FaEnvelope,
	'phone': FaPhone,
	'globe': FaGlobe,
	// Additional mappings
	'arrow-up': FaArrowUp,
	'arrow-down': FaArrowDown,
	'arrow-circle-left': FaArrowCircleLeft,
	'arrow-circle-right': FaArrowCircleRight,
	'arrow-circle-up': FaArrowCircleUp,
	'arrow-circle-down': FaArrowCircleDown,
	'chevron-left': FaChevronLeft,
	'chevron-right': FaChevronRight,
	'chevron-up': FaChevronUp,
	'chevron-down': FaChevronDown,
	'angle-left': FaAngleLeft,
	'angle-right': FaAngleRight,
	'angle-up': FaAngleUp,
	'angle-down': FaAngleDown,
	'bars': FaBars,
	'ellipsis': FaEllipsisH,
	'ellipsisV': FaEllipsisV,
	'external': FaExternalLinkAlt,
	'link': FaLink,
	'paperclip': FaPaperclip,
	'book': FaBook,
	'bookmark': FaBookmark,
	'file': FaFile,
	'file-alt': FaFileAlt,
	'folder': FaFolder,
	'folder-open': FaFolderOpen,
	'image': FaImage,
	'images': FaImages,
	'video': FaVideo,
	'music': FaMusic,
	'volume-up': FaVolumeUp,
	'volume-mute': FaVolumeMute,
	'microphone': FaMicrophone,
	'microphone-off': FaMicrophoneSlash,
	'headphones': FaHeadphones,
	'play-circle': FaPlayCircle,
	'pause': FaPause,
	'pause-circle': FaPauseCircle,
	'stop': FaStop,
	'step-forward': FaStepForward,
	'step-backward': FaStepBackward,
	'fast-forward': FaFastForward,
	'fast-backward': FaFastBackward,
	'redo': FaRedo,
	'undo': FaUndo,
	'sync': FaSync,
	'spinner': FaSpinner,
	'asterisk': FaAsterisk,
	'question': FaQuestionCircle,
	'infoAlt': FaInfo,
	'check-square': FaCheckSquare,
	'square': FaSquare,
	'th': FaTh,
	'th-large': FaThLarge,
	'th-list': FaThList,
	'list': FaList,
	'list-alt': FaListAlt,
	'table': FaTable,
	'chart-bar': FaChartBar,
	'chart-pie': FaChartPie,
	'chart-line': FaChartLine,
	'chart-area': FaChartArea,
	'map': FaMap,
	'map-marker': FaMapMarker,
	'map-marker-alt': FaMapMarkerAlt,
	'location-arrow': FaLocationArrow,
	'compass': FaCompass,
	'flag': FaFlag,
	'trophy': FaTrophy,
	'medal': FaMedal,
	'gift': FaGift,
	'shopping-cart': FaShoppingCart,
	'credit-card': FaCreditCard,
	'wallet': FaWallet,
	'dollar-sign': FaDollarSign,
	'euro-sign': FaEuroSign,
	'pound-sign': FaPoundSign,
	'yen-sign': FaYenSign,
	'bitcoin': FaBitcoin,
	'apple': FaApple,
	'android': FaAndroid,
	'windows': FaWindows,
	'linux': FaLinux,
	'github': FaGithub,
	'gitlab': FaGitlab,
	'bitbucket': FaBitbucket,
	'git': FaGit,
	'code-branch': FaCodeBranch,
	'code': FaCode,
	'bug': FaBug,
	'rocket': FaRocket,
	'cloud': FaCloud,
	'cloud-upload': FaCloudUploadAlt,
	'cloud-download': FaCloudDownloadAlt,
	'server': FaServer,
	'database': FaDatabase,
	'shield': FaShieldAlt,
	'key': FaKey,
	'unlock-alt': FaUnlockAlt,
	'user-circle': FaUserCircle,
	'users': FaUsers,
	'user-plus': FaUserPlus,
	'user-minus': FaUserMinus,
	'user-check': FaUserCheck,
	'user-times': FaUserTimes,
	'user-edit': FaUserEdit,
	'user-friends': FaUserFriends,
	'envelope-open': FaEnvelopeOpen,
	'at': FaAt,
	'comment': FaComment,
	'comments': FaComments,
	'paper-plane': FaPaperPlane,
	'bell-off': FaBellSlash,
	'calendar-alt': FaCalendarAlt,
	'calendar-check': FaCalendarCheck,
	'calendar-times': FaCalendarTimes,
	'clock': FaClock,
	'hourglass': FaHourglass,
	'history': FaHistory,
	'clipboard': FaClipboard,
	'tasks': FaTasks,
	'briefcase': FaBriefcase,
	'building': FaBuilding,
	'crown': FaCrown,
	'gem': FaGem,
	'lightbulb': FaLightbulb,
	'magic': FaMagic,
	'puzzle-piece': FaPuzzlePiece,
	'smile': FaSmile,
	'frown': FaFrown,
	'meh': FaMeh,
	'thumbs-up': FaThumbsUp,
	'thumbs-down': FaThumbsDown,
	'hand-paper': FaHandPaper,
	'hand-peace': FaHandPeace,
	'hand-point-up': FaHandPointUp,
	'hand-point-down': FaHandPointDown,
	'hand-point-left': FaHandPointLeft,
	'hand-point-right': FaHandPointRight,
	'arrow-alt-circle-up': FaArrowAltCircleUp,
	'arrow-alt-circle-down': FaArrowAltCircleDown,
	'arrow-alt-circle-left': FaArrowAltCircleLeft,
	'arrow-alt-circle-right': FaArrowAltCircleRight,
	'caret-up': FaCaretUp,
	'caret-down': FaCaretDown,
	'caret-left': FaCaretLeft,
	'caret-right': FaCaretRight,
	'chevron-circle-up': FaChevronCircleUp,
	'chevron-circle-down': FaChevronCircleDown,
	'chevron-circle-left': FaChevronCircleLeft,
	'chevron-circle-right': FaChevronCircleRight,
	'dot': FaDotCircle,
	'circle': FaCircle,
	'reg-circle': FaRegCircle,
	'reg-dot-circle': FaRegDotCircle,
	'reg-square': FaRegSquare,
	'reg-check-circle': FaRegCheckCircle,
	'reg-times-circle': FaRegTimesCircle,
	'reg-question-circle': FaRegQuestionCircle,
	'reg-smile': FaRegSmile,
	'reg-frown': FaRegFrown,
	'reg-meh': FaRegMeh,
	'reg-bell': FaRegBell,
	'reg-calendar-alt': FaRegCalendarAlt,
	'reg-clock': FaRegClock,
	'reg-comment': FaRegComment,
	'reg-envelope': FaRegEnvelope,
	'reg-file-alt': FaRegFileAlt,
	'reg-folder': FaRegFolder,
	'reg-image': FaRegImage,
	'reg-list-alt': FaRegListAlt,
	'reg-map': FaRegMap,
	'reg-paper-plane': FaRegPaperPlane,
	'reg-star': FaRegStar,
	'reg-user': FaRegUser,
};

export const ICONS_ALL_LIST = Object.keys(
	icons
) as IconName[];
